### ISSUE TITLE
git source clone, npm run dev, Cherry bookmarks have broken icons and NodeJS console error "Proxy opts.uri is mandatory"

### ISSUE THREAD

**Issue by RocketDerp** [haishanh/cherry#11]
Proxy opts.uri is mandatory
    InvalidArgumentError: Proxy opts.uri is mandatory
       at buildProxyOptions (...cherry/node_modules/undici/lib/proxy-agent.js:28:11)
       at new ProxyAgent (...cherry/node_modules/undici/lib/proxy-agent.js:40:20)
       at ...cherry/src/routes/api/favicon/[site]/favicon.util.ts:16:61

I'm not running with docker or anything, just git clone of the project, setup .env for database, I was able to create (email/SQLite local) account through the webapp, then after adding a bookmark this error is on the server-side when running localhost in browser.

EDIT: More information. It's the images are broken on all the bookmark. In Chrome I opened the Image link in another tab and it's like this: http://localhost:5173/api/favicon/old.reddit.com - which generates the server-side console error.

I'm not running within docker, running native on Ubuntu 22.04 development machine. Thank you.

**Comment by haishanh** [comment]
@RocketDerp I think I've fixed it in `main`, please check.

**Comment by RocketDerp** [comment]
I did a git pull and tried it again, but still seems to fail.

My .env has no setting for HTTP_PROXY, so i think it is coming out **undefined** instead of an empty string.

I hacked line 17 from:

     ? { dispatcher: new ProxyAgent(HTTP_PROXY) }

to just

    ? {undefined}

And it works. But if I do console.log right before this const fetchInit is defined:

    console.error("Hello World");
    console.error(process.env.NODE_ENV);
    console.error(HTTP_PROXY);

Both variables return **undefined**

**Comment by haishanh** [comment]
@RocketDerp mind try pull main and test it again?

**Comment by RocketDerp** [comment]
> @RocketDerp mind try pull main and test it again?

Ok, your 2nd attempt fixed it. Thank you. Closing issue.
