### ISSUE TITLE
Chrome browser, Bookmarklet works on Reddit page, but "fetch failed" on Twitter page

### ISSUE THREAD

**Issue by RocketDerp** [haishanh/cherry#12]
1. This works: https://old.reddit.com/r/AskReddit/comments/y01xtf/film_snobs_of_reddit_who_was_the_single_worst/irri5i5/ you get "Cherry Picked!"

2. This fails: https://twitter.com/Aishalee02/status/1576501603376324608 with "failed to fetch"

I'm running the Cherry app with "npm run dev" from git source checkout, localhost:xxx

The Chrome console says CORS issue when Bookmarklet is used on Twitter. Is Twitter blocking this?

**Comment by haishanh** [comment]
Yes, it's because Twitter applied a restrictive connect-src Content Security Policy. 
That's the limitation of the bookmarklet.
