### ISSUE TITLE
Feature Request: Docker image for raspberry pi

### ISSUE THREAD

**Issue by dgmltn** [haishanh/cherry#16]
Seems the Dockerfile here is close to working for raspberry pi, but it includes some specifically non-arm code. Is it possible to make it generic enough to work with Raspberry Pi?

**Comment by haishanh** [comment]
Which model of Raspberry Pi are you using?
I think the image should work on Raspberry Pi 4B at least, not tested tho.

**Comment by dgmltn** [comment]
Raspberry Pi 3. But I'll go ahead and close this request.

**Comment by theEpicjosh** [comment]
I know this issue is marked as closed, but I tested this on my Raspberry Pi 5 and it does not work. It gives me an Exec error.
