### ISSUE TITLE
Remote assets?

### ISSUE THREAD

**Issue by kartolo** [haishanh/cherry#18]
Hi,

is there any reason, why the favicons are not in the docker container, but instead are served directly from your server? this way you can get referrer to my installation.

Could you please put the favicon in the images and locally load them?

https://github.com/haishanh/cherry/blob/10fa73817869acb7536534f5374d462cc3c7e430/src/app.html#L6

**Comment by haishanh** [comment]
Ah...those remote favicons are rather temporary, just forgot to pull and serve them locally. Thanks for reporting.

**Comment by haishanh** [comment]
Addressed with https://github.com/haishanh/cherry/commit/b55840b19164bcf30e1712edf86cd9b4822cce65. It's in latest version (`v0.0.6`) now.
