### ISSUE TITLE
signin stop

### ISSUE THREAD

**Issue by 78Rcastro** [haishanh/cherry#19]
Hi there. 
When i sign, IT stays in that page. Cant do anything more it stays static
The credencial are correct, i made previous registry them. 
Thanks

**Comment by haishanh** [comment]
You may set env var `USE_INSECURE_COOKIE` to `1` and see if that works.

**Comment by HKlinoDE** [comment]
Setting the env var worked for me.
(running in synology docker)
Thanks!
