### ISSUE TITLE
I can't search Chinese, only the English part of the bookmark title

### ISSUE THREAD

**Issue by m1732948116** [haishanh/cherry#31]
I can't search Chinese, only the English part of the bookmark title.Hopefully this feature can be added.

**Comment by haishanh** [comment]
It should've been improved a bit in the latest version.

```sh
docker pull ghcr.io/haishanh/cherry:v0.0.8
```

**Comment by m1732948116** [comment]
> It should've been improved a bit in the latest version.
> 
> ```shell
> docker pull ghcr.io/haishanh/cherry:v0.0.8
> ```

 感谢大佬无私奉献，已经用上啦
