### ISSUE TITLE
FR: SSO by Proxy authentication

### ISSUE THREAD

**Issue by dorianim** [haishanh/cherry#6]
### Describe the feature you would like to see.

It would be nice to allow authentication via an HTTP-header containing the username. This would allow using proxy authentication via sso providers like [Authelia](https://github.com/authelia/authelia) or [Authentik](https://github.com/goauthentik/authentik) and by this, it would also be possible to authenticate using ldap or oidc.

### Describe the solution you'd like.

- New environment variables for:
  - Whether the header authentication should be enabled
  - The header containing the username of the user
  - The header containing the email of the user
- Automatic account creation for new users, this can happen transparently

### Additional context to this request.

Proxy authentication basically works like this:
- You put a proxy in front of your application
- This proxy does not let anything through to the application until the user authenticates with the proxy
- As soon as the user is authenticated, the proxy passes the traffic to the application including a header containing their username, email and whatever else you configure
- Authentication for apps like the browser extension can be handled by creating an API-token which can be used to authenticated to the api when no heder is present

OpenID Connect would also be a good option, but this is much simpler to implement.

Many other services do this as well, for example [Paperless](https://paperless-ngx.readthedocs.io/en/latest/configuration.html?highlight=PAPERLESS_ENABLE_HTTP_REMOTE_USER#hosting-security)
and [Firefly III](https://docs.firefly-iii.org/firefly-iii/advanced-installation/authentication/#remote-user)

I'd really like to have some form of SSO, as I host many services for myself and don't like to sue different credentials for everything. And it should not be too complicated to implement :slightly_smiling_face: What do you think?

**Comment by haishanh** [comment]
This is now supported in the latest version (`v0.0.5`). Related env vars are `ENABLE_HTTP_REMOTE_USER` and `HTTP_REMOTE_USER_HEADER_NAME`, more details in the [docs](https://cherry.haishan.me/docs/deploy#environment-variables).

There is also a demo setup in [docker/examples/authelia-forward-auth](https://github.com/haishanh/cherry/tree/main/docker/examples/authelia-forward-auth) that uses Authelia and Caddy.

**Comment by dorianim** [comment]
Thanks! I can confirm it works with Authentik and Trafik :)
