### ISSUE TITLE
Add a keyboard shortcut to save a link if possible

### ISSUE THREAD

**Issue by mrg358** [haishanh/cherry#7]
Regarding UX, not sure if possible, a keyboard shortcut for browser extension to save a link would be super useful.

**Comment by haishanh** [comment]
That's definitely possible. Probably the real challenge is to find a good keyboard shortcut combo. I'll check.

**Comment by haishanh** [comment]
Implemented. The default shortcut is `Ctrl+Shift+E` (`Cmd+Shift+E` on mac). 

---

In case you want to customize the shortcut:

If you are using Chrome, go to chrome://extensions/shortcuts 
<img width="482" alt="image" src="https://user-images.githubusercontent.com/1166872/196390668-7ee68a58-ace3-4290-88dd-95a84727207f.png">


On Firefox, go to manage extension page:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/1166872/196390096-feeb1b4f-f7c0-4b7e-9b9e-af1cfd9cd992.png">
