### ISSUE TITLE
Issue with deletion bookmarks

### ISSUE THREAD

**Issue by Ombrelin** [haishanh/cherry#8]
When I : 
1. Delete a bookmark
2. Edit and save another bookmark
Then the bookmark I deleted re-appears, until the page is refreshed. 
Demo of the problem : 
![Peek 2022-10-09 21-36](https://user-images.githubusercontent.com/47502331/194776215-02c7e7fc-6171-44a8-98e9-3231651ad9bb.gif)

**Comment by haishanh** [comment]
It's fixed now. There's a frontend state inconsistency issue previously.

Thanks for report. Really appreciate the demo GIF!
