### ISSUE TITLE
Extension Feature Requests: Shortcut to cherry webpage and already favorited indicator

### ISSUE THREAD

**Issue by r3Fuze** [haishanh/cherry#9]
Hi, I have two feature requests for the browser extension.

One is a way to get to the cherry webpage through the extension icon. Some of my other extensions have a right click menu with custom entries so it should be possible to add a small shortcut there. (I'm using Firefox, I don't know if Chrome can do the same)

The other request is adding a small icon (like a star) in the corner of the extension icon so you know if you've already favorited a page. I have other extensions that show a number on their icon (uBlock Origin shows blocked ads, Bitwarden shows how many saved passwords for a page) but I don't know if that's a feature built in to Firefox and if it is limited to just numbers.

Loving everything else about Cherry so far, good job

**Comment by haishanh** [comment]
Implemented. It should be available on Firefox very soon, but will take time on Chrome.

The shortcut is `Control+Shift+E` (`Cmd+Shift+E` on macOS) and can be customized on both Firefox and Chrome.

I tried to add a star to the right bottom of the "cherry" icon, but just doesn't look great. I end up use the "leaf" icon as the default icon and "cherry" as the picked indicator icon.
